### ISSUE TITLE
Filter stateful scenes by label

### ISSUE THREAD

**Issue by teetow** [hugobloem/stateful_scenes#179]
As far as I can tell, a stateful scene switch can be assigned a label in the UI, but the data doesn't seem to show up, nor does it seem possible to filter on label in cards like `auto-entities`. Would be helpful if it could.

**Comment by hugobloem** [comment]
Hi, this does seem to work for me. Either label the device or the switch entity, and then use the following auto-entities configuration:

```yaml
type: custom:auto-entities
card:
  type: grid
  square: false
  columns: 2
card_param: cards
filter:
  include:
    - label: Stateful Scene
      options:
        type: tile
        tap_action:
          action: toggle
  exclude:
    - entity_category: config
    - entity_category: diagnostic
sort:
  method: last_changed
  reverse: true
  numeric: true
  count: 6
```
