### ISSUE TITLE
'Unknown error occurred' when adding integration

### ISSUE THREAD

**Issue by barryvdh** [hugobloem/stateful_scenes#34]
I've installed this module with HACS, but when I add the integration, it shows this error:
<img width="499" alt="image" src="https://github.com/hugobloem/stateful_scenes/assets/973269/e61ed21e-9228-451a-b397-8fa2b8a4ac53">

My scenes.yaml:

<details>

```yaml

- id: '1702407733767'
  name: Helder
  entities:
    light.beneden:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4504
      min_mireds: 222
      max_mireds: 454
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 204
      color_temp_kelvin: 2570
      color_temp: 389
      hs_color:
      - 28.696
      - 70.045
      rgb_color:
      - 255
      - 161
      - 76
      xy_color:
      - 0.54
      - 0.388
      is_hue_group: true
      hue_scenes:
      - Helder
      - Gedimd
      - Ontspannen
      hue_type: zone
      lights:
      - Keuken spot 2
      - Kast
      - Slaapkamer Ouders
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Beneden
      supported_features: 40
      state: 'on'
  icon: mdi:lamps
  metadata:
    light.beneden:
      entity_only: true
- id: '1702491911767'
  name: Avond
  entities:
    light.beneden:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 4504
      min_mireds: 222
      max_mireds: 454
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 166
      color_temp_kelvin: 2202
      color_temp: 454
      hs_color:
      - 29.79
      - 84.553
      rgb_color:
      - 255
      - 146
      - 39
      xy_color:
      - 0.579
      - 0.388
      is_hue_group: true
      hue_scenes:
      - Helder
      - Gedimd
      - Ontspannen
      hue_type: zone
      lights:
      - Keuken spot 2
      - Kast
      - Slaapkamer Ouders
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Beneden
      supported_features: 40
      state: 'on'
  icon: mdi:lamps
  metadata:
    light.beneden:
      entity_only: true

```
</details>

I'm not really sure how to debug this though. The scenes work fine. Maybe because it's a Hue group?
