### ISSUE TITLE
Use scenes from Hue

### ISSUE THREAD

**Issue by barryvdh** [hugobloem/stateful_scenes#35]
I have a lot of scenes in Hue. Is it possible to get the scenes from there?

The scene does have brightness setting:

I think that roughly matches (if the temperature in lights is 0-255 instead of 0-100?)
<img width="1064" alt="image" src="https://github.com/hugobloem/stateful_scenes/assets/973269/0a712abc-cdac-46a1-857d-e2dca787fe5d">

What I do now is create a template that calls the scene, but shows the state from your scene.
```
type: grid
cards:
  - type: custom:mushroom-template-card
    entity: switch.helder_stateful_scene
    tap_action:
      action: call-service
      service: scene.turn_on
      target:
        entity_id:
          - scene.helder
        device_id: []
        area_id: []
    icon: hue:scene-bright
    primary: Helder
    multiline_secondary: true
    secondary: '{{  bool(states(entity)) | iif(''Aan'', ''Uit'')}}'
    icon_color: '{{ iif(bool(states(entity)), ''orange'', ''grey'') }}'
 ```

Which now calls the scene I created in HA, but that wouldn't be necessary in that case. But not sure how reliable it is.

(I used the call-service instead of the toggle because that seemed more reliable, to force the state even if already active)
